my_string = input("Ваш текст: ")
number_of_characters = len(my_string)
print("Количество символов введённого текста: ",number_of_characters)
my_string = "Практическое задание"
print(my_string. upper())
print(my_string. lower())
print(my_string[0])
print(my_string[-1])
my_string = my_string.replace(" ", "")
print(my_string)